#!/usr/bin/env bash
set -euo pipefail
cd /c/Users/ameen/repos/ai-mise
R="boulaajaj/ai-mise"

git add -A
git -c user.name='Amine Boulaajaj' -c user.email='ameen.b@gmail.com' commit -q -m 'Phase 0: policy schema + validator (#2), worked schema examples (#3), baseline capture scaffolding (#1)'
git push -q
echo PUSHED

gh issue close 2 -R "$R" -c "Done. policy.schema.json (Draft 2020-12) + validate_policy.py (graceful degradation without jsonschema/pyyaml; cross-field shadow-mode invariant). Validation evidence: policy.yaml validates clean in full-jsonschema mode; a deliberately broken policy (auto_approve non-empty under shadow mode) is rejected by both the schema and the invariant check."
gh issue close 3 -R "$R" -c "Done. 5 worked examples in control-plane/approval/examples/: routine/structural/safety proposals + approved-with-modifications and rejected receipts (rejection_reason feeds rejection learning). All 5 validate clean against proposal.schema.json / receipt.schema.json (jsonschema Draft 2020-12). No schema friction found; schemas unchanged."
gh issue comment 1 -R "$R" -b "Prep done: control-plane/evaluation/baselines/README.md has exact capture commands for both baselines. Remaining work needs Amine at the machine interactively: run /init (and CLAUDE_CODE_NEW_INIT=1) on the Arduino Digger repo, snapshot the manual workspace, fill both NOTES.md."
echo ISSUES-CLOSED

gh issue create -R "$R" --title "Decide retrospective cadence policy (event-driven + scheduled + trajectory)" --milestone "Phase 5 — Retrospective Shadow Mode" --body "From Amine: how many retrospectives — daily, weekly? Proposed default (all configurable in policy.yaml): event-driven micro-retrospective after any session with a correction; weekly scheduled retrospective; trajectory review every 10th retrospective or monthly (existing policy defaults). Validate the cadence empirically during the Arduino golden thread and adjust the defaults from observed correction volume, not theory." >/dev/null
gh issue create -R "$R" --title "Design: lenses over one shared context instead of duplicated subagent contexts" --milestone "Phase 3 — Claude Code Adapter" --body "From Amine: when a large context (memory + documents) is loaded, manage it as ONE shared substrate used across lenses/agents rather than duplicating it per agent. Direction: the workspace filesystem IS the shared context (progressive disclosure means every agent reads the same files on demand); 'lenses' = multiple passes with different instructions over the same cached substrate — subagents reserved for when isolation is genuinely needed (untrusted content, parallel bulk work). Leverage prompt caching. Study how OpenHarness and deepagents handle subagent context handoff. Output: a decision note or ADR-0006 with the lens-vs-agent rubric the Builder applies when generating orchestration." >/dev/null
gh issue create -R "$R" --title "Second-mind layer: Obsidian-compatible views + provenance-backed knowledge graph" --milestone "Phase 4 — Evidence-Backed Knowledge" --body "From Amine: include a 'second mind' — a living map of the person's/project's thinking. Decision direction: do NOT build a mind-map engine; make views/wiki Obsidian-compatible (wikilinks, plain markdown, vault-openable folder) so graph view / mind map comes free in Obsidian, on top of our claims layer — giving us what no PKM tool has: every node traceable to evidence (ADR-0002). Prior art to study before building: khoj-ai/khoj (AI second brain, self-hostable), AgriciDaniel/claude-obsidian and Ar9av/obsidian-wiki (Karpathy LLM-wiki pattern in Obsidian), eugeniughelbur/obsidian-second-brain (cross-CLI vault skill, 45 commands). Reuse their vault conventions; our differentiator is provenance + governance underneath the graph." >/dev/null
gh issue create -R "$R" --title "Outfitting: research and recommend tools/MCPs/skills per domain, security-screened" --body "From Amine: the Builder should discover what the workspace NEEDS, not just organize what exists — research current best tools, MCP connectors, and skills for the domain from reputable registries and curated lists (awesome-harness-engineering, best-of-Agent-Harnesses, official MCP registry, anthropics/skills), screen candidates for vulnerabilities and prompt-injection (metaharness mcp-scan pattern; prior-art.md reuse decision 2's default-deny policy), and present recommendations with provenance for approval like any transaction. Backlog: sequence after Phase 1 proves inspection; this extends Acquire/Inspect into 'research the domain A-to-Z' for any profession (law, medicine, hardware)." >/dev/null
gh issue create -R "$R" --title "Completeness model + readiness dashboard (gate harness generation on it)" --milestone "Phase 1 — Read-Only Bootstrapper" --body "From Amine: generalize the unknowns ledger into a completeness model — the set of things that make a workspace ready (profile, organization, mission, constraints, safety items, resources, recurring work, preferences...), each marked known / assumed / missing, with a visible dashboard: what the Builder already understands vs still needs ('you told me about your company but nothing about yourself; your mission is unclear'). Harness generation is gated on completeness: only when required items are known or explicitly assumed does the Builder compile. The dashboard is also the non-technical progress surface. Design the item taxonomy per domain layer (universal / profession / organization / personal — original synthesis section 7)." >/dev/null
echo NEW-ISSUES-FILED

ls /c/Users/ameen/repos | head -30
rm -- "$0"
